import type { Candidate } from "@/lib/types";

export const DEMO_CANDIDATES: Candidate[] = [
  {
    id: "cand-aigerim-bekova",
    code: "IU-2601",
    name: "Aigerim Bekova",
    city: "Almaty",
    program: "Social Entrepreneurship",
    status: "shortlisted",
    final_score: 89.4,
    cognitive: 86,
    leadership: 91,
    growth: 90,
    decision: 84,
    motivation: 94,
    authenticity: 88,
    confidence: 0.91,
    ai_detection_prob: 0.14,
    ai_signals: ["Natural speech pattern", "Consistent story across artifacts", "Specific local examples"],
    needs_manual_review: false,
    reasoning: "Strong leadership, clear public impact and well-supported evidence across interview and artifacts.",
    key_quotes: [
      "I want to build a system that keeps working after I step away.",
      "After our first failure, I returned to the team and rebuilt the project around a clearer goal.",
    ],
    goals: "Launch a regional network of school micro-labs for social projects.",
    experience: "Led a volunteer team, attracted sponsors and ran a city-level civic project.",
    motivation_text: "Sees inVision U as a place to grow from initiative into systems-level leadership.",
    essay_excerpt: "Leadership starts when you stay after the failure and gather people again.",
    artifacts: [
      {
        id: "art-aig-doc",
        kind: "document",
        name: "portfolio-aigerim.pdf",
        mimeType: "application/pdf",
        sizeKb: 420,
        transcript: "Portfolio with impact metrics, partnerships and letters of support.",
        extractedSignals: ["400+ participants", "school partnerships", "repeatable playbook"],
        evidenceWeight: 0.34,
      },
      {
        id: "art-aig-video",
        kind: "video",
        name: "motivation-video.mp4",
        mimeType: "video/mp4",
        sizeKb: 18240,
        transcript: "Video answer with concrete examples of leadership and reflection after setbacks.",
        extractedSignals: ["authentic delivery", "clear ownership", "strong reflection"],
        evidenceWeight: 0.29,
      },
    ],
    committee_review: {
      requiredApprovals: 3,
      votes: [
        { memberId: "cm-1", memberName: "Aliya Nurlanova", decision: "approve", rationale: "Strong evidence and mature motivation.", createdAt: "2026-04-05T09:00:00.000Z" },
        { memberId: "cm-2", memberName: "Ruslan Zhumabek", decision: "approve", rationale: "Rare balance of leadership and public value.", createdAt: "2026-04-05T09:04:00.000Z" },
        { memberId: "cm-3", memberName: "Dina Kassenova", decision: "approve", rationale: "Artifacts confirm the claimed track record.", createdAt: "2026-04-05T09:06:00.000Z" },
      ],
      approvedCount: 3,
      rejectCount: 0,
      holdCount: 0,
      finalDecision: "approved",
      corruptionGuard: "No one can admit a candidate alone. This profile is backed by three independent approvals.",
    },
    explainability_v2: {
      verdict: "Recommended for approval",
      plainLanguage: "The candidate combines high leadership, strong motivation and low authenticity risk.",
      evidence: [
        { title: "Project ownership", summary: "Describes a real launch with measurable results.", supports: ["leadership", "growth"] },
        { title: "Mission clarity", summary: "Motivation is tied to a concrete public problem.", supports: ["motivation", "authenticity"] },
      ],
      modelContributions: [
        { model: "baseline", score: 85, weight: 0.3, rationale: "Clear story and measurable experience." },
        { model: "llm_scorer", score: 91, weight: 0.45, rationale: "High leadership and mature reflection." },
        { model: "artifact_review", score: 90, weight: 0.25, rationale: "Artifacts support the claimed impact." },
      ],
      fairnessNotes: [
        "Protected traits and social-economic signals were excluded from scoring.",
        "The result is driven by content, evidence and consistency across sources.",
      ],
    },
  },
  {
    id: "cand-daniyar-seitqali",
    code: "IU-2602",
    name: "Daniyar Seitqali",
    city: "Astana",
    program: "AI & Society",
    status: "flagged",
    final_score: 81.2,
    cognitive: 92,
    leadership: 73,
    growth: 82,
    decision: 84,
    motivation: 74,
    authenticity: 63,
    confidence: 0.62,
    ai_detection_prob: 0.71,
    ai_signals: ["High polish in written answers", "Style mismatch across channels", "Strong product evidence but uneven authenticity"],
    needs_manual_review: true,
    reasoning: "Technically exceptional candidate with real traction, but this profile needs manual review because AI-risk is high.",
    key_quotes: [
      "I want to build tools that help farmers make better decisions with data.",
      "I need a stronger leadership environment to grow beyond execution.",
    ],
    goals: "Create regional agri-tech solutions for small and mid-sized farms.",
    experience: "Built a farming app, won grant funding and reached real users.",
    motivation_text: "Looks like a high-upside candidate if authenticity concerns are resolved.",
    essay_excerpt: "I want to grow from a strong builder into a system-level leader.",
    committee_review: {
      requiredApprovals: 3,
      votes: [{ memberId: "cm-1", memberName: "Aliya Nurlanova", decision: "hold", rationale: "Needs a live clarification on authorship and role.", createdAt: "2026-04-05T09:10:00.000Z" }],
      approvedCount: 0,
      rejectCount: 0,
      holdCount: 1,
      finalDecision: "escalated",
      corruptionGuard: "High AI-risk automatically triggers a committee-level manual review instead of auto rejection.",
    },
  },
  {
    id: "cand-malika-tasova",
    code: "IU-2603",
    name: "Malika Tasova",
    city: "Shymkent",
    program: "Education Leadership",
    status: "completed",
    final_score: 73.8,
    cognitive: 71,
    leadership: 76,
    growth: 75,
    decision: 70,
    motivation: 86,
    authenticity: 78,
    confidence: 0.83,
    ai_detection_prob: 0.22,
    ai_signals: ["Personal motivation", "Practical community case", "Needs stronger metrics"],
    needs_manual_review: false,
    reasoning: "A high-heart, medium-structure profile. Strong mission fit, but not yet a top-ranked finalist.",
    key_quotes: [
      "I want to reform early childhood education through partnerships, not slogans.",
      "I listen first and then design a format people want to join.",
    ],
    goals: "Improve early childhood education through local parent and teacher partnerships.",
    experience: "Led a teaching club and ran practical sessions for future educators.",
    motivation_text: "Strong mission fit and good public-service motivation.",
    essay_excerpt: "People join change when they can see the first step, not just the vision.",
    committee_review: {
      requiredApprovals: 3,
      votes: [],
      approvedCount: 0,
      rejectCount: 0,
      holdCount: 0,
      finalDecision: "pending",
      corruptionGuard: "No profile enters the final shortlist without committee validation.",
    },
  },
  {
    id: "cand-arman-zhaksybekov",
    code: "IU-2604",
    name: "Arman Zhaksybekov",
    city: "Almaty",
    program: "Public Leadership",
    status: "shortlisted",
    final_score: 69.7,
    cognitive: 74,
    leadership: 68,
    growth: 70,
    decision: 72,
    motivation: 65,
    authenticity: 67,
    confidence: 0.77,
    ai_detection_prob: 0.31,
    ai_signals: ["Split committee signal", "Strong initiative", "Mission fit still debated"],
    needs_manual_review: true,
    reasoning: "Interesting but disputed candidate. The initiative is real, while mission alignment still needs discussion.",
    key_quotes: [
      "I want regional founders to have access to capital they usually never see.",
      "When the club started losing people, I changed the meeting format and brought them back.",
    ],
    goals: "Build better access to opportunity and capital for regional founders.",
    experience: "Interned in venture, founded a student investment club and changed its participation model.",
    motivation_text: "Potentially valuable profile, but a more explicit public-purpose narrative is needed.",
    essay_excerpt: "Sometimes change starts with one format people actually want to return to.",
    committee_review: {
      requiredApprovals: 3,
      votes: [
        { memberId: "cm-1", memberName: "Aliya Nurlanova", decision: "approve", rationale: "Strong initiative and clear proof of action.", createdAt: "2026-04-05T09:20:00.000Z" },
        { memberId: "cm-2", memberName: "Ruslan Zhumabek", decision: "hold", rationale: "Still need better mission alignment.", createdAt: "2026-04-05T09:24:00.000Z" },
      ],
      approvedCount: 1,
      rejectCount: 0,
      holdCount: 1,
      finalDecision: "escalated",
      corruptionGuard: "Split-vote candidates are escalated for collective discussion before any final outcome.",
    },
  },
  {
    id: "cand-zarina-nurmagambet",
    code: "IU-2605",
    name: "Zarina Nurmagambet",
    city: "Pavlodar",
    program: "Youth Wellbeing",
    status: "in_progress",
    final_score: 64.1,
    cognitive: 66,
    leadership: 71,
    growth: 76,
    decision: 61,
    motivation: 82,
    authenticity: 81,
    confidence: 0.69,
    ai_detection_prob: 0.17,
    ai_signals: ["High authenticity", "Strong mission fit", "Profile not complete yet"],
    needs_manual_review: false,
    reasoning: "Promising hidden gem with strong authenticity and growth potential, but the interview is not complete yet.",
    key_quotes: [
      "Mental-health support should not be a luxury for young people in small towns.",
      "I have the energy and the mission, but I need stronger structure to scale it.",
    ],
    goals: "Build an accessible mental-health support network for youth in small cities.",
    experience: "Volunteer in a crisis center and host of a youth wellbeing podcast.",
    motivation_text: "Clear mission-led profile with visible potential for growth.",
    essay_excerpt: "I see not only the problem, but the moment when people stop believing that help can be close.",
    committee_review: {
      requiredApprovals: 3,
      votes: [],
      approvedCount: 0,
      rejectCount: 0,
      holdCount: 0,
      finalDecision: "pending",
      corruptionGuard: "Incomplete profiles cannot be treated as final candidates and stay outside final decisions.",
    },
  },
];
