import type { Candidate } from "@/lib/types";

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: "cand-aigerim-bekova",
    code: "IU-2601",
    name: "Айгерим Бекова",
    city: "Алматы",
    program: "Social Entrepreneurship",
    status: "shortlisted",
    final_score: 89.4,
    cognitive: 86,
    leadership: 91,
    growth: 90,
    decision: 84,
    motivation: 94,
    authenticity: 88,
    confidence: 0.91,
    ai_detection_prob: 0.14,
    ai_signals: [
      "Речь последовательная и естественная",
      "В ответах есть локальные детали и личные примеры",
      "Стиль стабилен между анкетой, интервью и документами",
    ],
    needs_manual_review: false,
    reasoning: "Сильный кандидат с доказанным лидерством, высокой мотивацией и хорошей способностью масштабировать социальную инициативу. Рекомендован к одобрению.",
    key_quotes: [
      "Я не хочу просто выиграть грант, мне важно выстроить систему, которая переживет меня.",
      "Когда первый проект провалился, я вернулась к людям и заново собрала команду вокруг цели.",
    ],
    goals: "Запустить сеть школьных микролабораторий по социальным проектам в регионах Казахстана.",
    experience: "Руководила волонтерской командой из 40 человек, привлекла спонсоров и провела городской экологический проект.",
    motivation_text: "Выбирает inVision U как среду для роста в социальном предпринимательстве и системном лидерстве.",
    essay_excerpt: "Лидерство начинается не на сцене, а в момент, когда после ошибки ты остаешься и собираешь людей снова.",
    artifacts: [
      {
        id: "art-aig-doc",
        kind: "document",
        name: "portfolio-aigerim.pdf",
        mimeType: "application/pdf",
        sizeKb: 420,
        transcript: "Портфолио с кейсами экологических инициатив, метриками участия и письмами поддержки.",
        extractedSignals: ["3 проекта", "400+ участников", "партнерства со школами"],
        evidenceWeight: 0.34,
      },
      {
        id: "art-aig-video",
        kind: "video",
        name: "motivation-video.mp4",
        mimeType: "video/mp4",
        sizeKb: 18240,
        transcript: "Видео-обращение с конкретными примерами лидерства и рефлексией после провала первого запуска.",
        extractedSignals: ["естественная речь", "уверенный контакт", "личная рефлексия"],
        evidenceWeight: 0.29,
      },
    ],
    explainability_v2: {
      verdict: "Рекомендуется к одобрению",
      plainLanguage: "Кандидат показывает сочетание лидерства, мотивации и устойчивого потенциала роста без значимых рисков по аутентичности.",
      evidence: [
        { title: "Руководство проектом", summary: "Описывает запуск городской инициативы с измеримым результатом.", supports: ["leadership", "growth"] },
        { title: "Мотивация", summary: "Мотивация связана с конкретной общественной проблемой, а не только с личной выгодой.", supports: ["motivation", "authenticity"] },
      ],
      modelContributions: [
        { model: "baseline", score: 85, weight: 0.3, rationale: "Высокая связность истории и хорошие метрики опыта." },
        { model: "llm_scorer", score: 91, weight: 0.45, rationale: "Сильные примеры лидерства и зрелая рефлексия." },
        { model: "artifact_review", score: 90, weight: 0.25, rationale: "Документы и видео подтверждают заявленные достижения." },
      ],
      fairnessNotes: [
        "В scoring не использовались пол, внешний вид и социально-экономический статус.",
        "Основной вклад дали содержание ответов, измеримые результаты и подтверждающие артефакты.",
      ],
    },
    committee_review: {
      requiredApprovals: 3,
      votes: [
        { memberId: "cm-1", memberName: "Алия Нурланова", decision: "approve", rationale: "Сильная доказательная база и зрелая мотивация.", createdAt: "2026-04-05T09:00:00.000Z" },
        { memberId: "cm-2", memberName: "Руслан Жумабек", decision: "approve", rationale: "Редкий баланс лидерства и общественной пользы.", createdAt: "2026-04-05T09:04:00.000Z" },
        { memberId: "cm-3", memberName: "Дина Касенова", decision: "approve", rationale: "Артефакты подтверждают глубину опыта.", createdAt: "2026-04-05T09:06:00.000Z" },
      ],
      approvedCount: 3,
      rejectCount: 0,
      holdCount: 0,
      finalDecision: "approved",
      corruptionGuard: "Кандидат не может быть принят единоличным решением: итог подтвержден тремя независимыми голосами комиссии.",
    },
    created_at: "2026-04-04T10:00:00.000Z",
    updated_at: "2026-04-05T09:06:00.000Z",
  },
  {
    id: "cand-daniyar-seitqali",
    code: "IU-2602",
    name: "Данияр Сейткали",
    city: "Астана",
    program: "AI & Society",
    status: "flagged",
    final_score: 81.2,
    cognitive: 92,
    leadership: 73,
    growth: 82,
    decision: 84,
    motivation: 74,
    authenticity: 63,
    confidence: 0.62,
    ai_detection_prob: 0.71,
    ai_signals: [
      "Часть ответов звучит слишком полированно",
      "Между эссе и устными ответами есть стилистический разрыв",
      "Технические достижения убедительны, но личные примеры местами поверхностны",
    ],
    needs_manual_review: true,
    reasoning: "Технически очень сильный кандидат, но профиль требует ручной верификации из-за высокого AI risk и неравномерной аутентичности.",
    key_quotes: [
      "Я хочу делать технологии, которые помогают фермерам принимать решения на основе данных.",
      "Мне не хватает системной школы лидерства, и именно за этим я иду в программу.",
    ],
    goals: "Разработать tech-решения для автоматизации сельского хозяйства в регионах Казахстана.",
    experience: "Создал приложение для фермеров, получил грант и довел продукт до сотен пользователей.",
    motivation_text: "Ищет среду, где сможет вырасти из сильного исполнителя в продуктового лидера.",
    essay_excerpt: "Мне важно научиться не только делать продукт, но и строить вокруг него команду и стратегию.",
    artifacts: [
      {
        id: "art-dan-doc",
        kind: "document",
        name: "farmhelper-case.pdf",
        mimeType: "application/pdf",
        sizeKb: 510,
        transcript: "Описание продукта FarmHelper с метриками внедрения и отзывами фермеров.",
        extractedSignals: ["500+ пользователей", "грант", "MVP-to-pilot"],
        evidenceWeight: 0.31,
      },
      {
        id: "art-dan-audio",
        kind: "audio",
        name: "voice-answer.webm",
        mimeType: "audio/webm",
        sizeKb: 820,
        transcript: "Голосовой ответ на кейс о региональной доступности технологий.",
        extractedSignals: ["нормальный темп речи", "уверенность", "низкая вариативность формулировок"],
        evidenceWeight: 0.18,
      },
    ],
    explainability_v2: {
      verdict: "Требует ручной проверки",
      plainLanguage: "Потенциал и результативность высокие, но система обнаружила конфликт между сильными достижениями и неоднородной аутентичностью ответов.",
      evidence: [
        { title: "Продуктовый кейс", summary: "Есть понятный кейс с пользователями и бизнес-ценностью.", supports: ["cognitive", "decision"] },
        { title: "AI risk", summary: "Часть письменных ответов выглядит более полированной, чем устные ответы и живые формулировки.", supports: ["authenticity"] },
      ],
      modelContributions: [
        { model: "baseline", score: 80, weight: 0.35, rationale: "Высокая когнитивная часть и хорошие сигналы по решениям." },
        { model: "llm_scorer", score: 83, weight: 0.4, rationale: "Реальные кейсы повышают общий балл." },
        { model: "ai_detection", score: 58, weight: 0.25, rationale: "Наличие искусственно сглаженных фрагментов снижает итоговую уверенность." },
      ],
      fairnessNotes: [
        "Флаг выставлен не по происхождению или профилю кандидата, а по конфликту между источниками данных.",
        "Кандидат не отклоняется автоматически: включается manual review.",
      ],
    },
    committee_review: {
      requiredApprovals: 3,
      votes: [
        { memberId: "cm-1", memberName: "Алия Нурланова", decision: "hold", rationale: "Нужно живое уточнение по кейсам и роли кандидата.", createdAt: "2026-04-05T09:10:00.000Z" },
      ],
      approvedCount: 0,
      rejectCount: 0,
      holdCount: 1,
      finalDecision: "escalated",
      corruptionGuard: "При низкой уверенности и высоком AI risk система автоматически требует коллегиальный manual review.",
    },
    created_at: "2026-04-04T10:10:00.000Z",
    updated_at: "2026-04-05T09:10:00.000Z",
  },
  {
    id: "cand-malika-tasova",
    code: "IU-2603",
    name: "Малика Тасова",
    city: "Шымкент",
    program: "Education Leadership",
    status: "completed",
    final_score: 73.8,
    cognitive: 71,
    leadership: 76,
    growth: 75,
    decision: 70,
    motivation: 86,
    authenticity: 78,
    confidence: 0.83,
    ai_detection_prob: 0.22,
    ai_signals: [
      "Мотивация последовательная и личная",
      "Есть практический кейс вовлечения сообщества",
      "Нужно больше метрик результата",
    ],
    needs_manual_review: false,
    reasoning: "Кандидатка пока уступает топ-профилям по стратегической глубине, но выделяется сильной мотивацией и общественной направленностью.",
    key_quotes: [
      "Я хочу реформировать дошкольное образование не через лозунги, а через работающие партнерства.",
      "Сначала я слушаю людей, а потом собираю формат, в который им хочется входить.",
    ],
    goals: "Развивать систему дошкольного образования через локальные партнерства и сообщества родителей.",
    experience: "Руководила педагогическим клубом и проводила практические сессии для будущих учителей.",
    motivation_text: "Ищет программу, которая даст структуру, менторство и инструменты масштабирования общественного проекта.",
    essay_excerpt: "Люди подключаются к изменениям не тогда, когда их зовут на реформу, а когда им показывают понятный первый шаг.",
    artifacts: [
      {
        id: "art-mal-doc",
        kind: "document",
        name: "education-plan.docx",
        mimeType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        sizeKb: 260,
        transcript: "План программы обучения родителей и воспитателей в южных регионах.",
        extractedSignals: ["community design", "teacher support", "low-cost rollout"],
        evidenceWeight: 0.27,
      },
    ],
    committee_review: {
      requiredApprovals: 3,
      votes: [],
      approvedCount: 0,
      rejectCount: 0,
      holdCount: 0,
      finalDecision: "pending",
      corruptionGuard: "Профиль ожидает обсуждения комиссии и не может перейти в shortlist без коллективного решения.",
    },
    created_at: "2026-04-04T10:20:00.000Z",
    updated_at: "2026-04-05T08:50:00.000Z",
  },
  {
    id: "cand-arman-zhaksybekov",
    code: "IU-2604",
    name: "Арман Жаксыбеков",
    city: "Алматы",
    program: "Public Leadership",
    status: "shortlisted",
    final_score: 69.7,
    cognitive: 74,
    leadership: 68,
    growth: 70,
    decision: 72,
    motivation: 65,
    authenticity: 67,
    confidence: 0.77,
    ai_detection_prob: 0.31,
    ai_signals: [
      "Финансовая и карьерная мотивация сильнее социальной",
      "Есть реальные примеры клубной инициативы",
      "Профиль разделил мнения комиссии",
    ],
    needs_manual_review: true,
    reasoning: "Спорный, но интересный кандидат: показывает инициативу и способность влиять на среду, но пока неочевидно, насколько его цели совпадают с ценностями программы.",
    key_quotes: [
      "Я хочу дать региональным стартапам доступ к капиталу, которого им обычно не хватает.",
      "Когда клуб начал терять людей, я изменил формат встреч и вернул интерес через живые питч-сессии.",
    ],
    goals: "Развивать инструменты поддержки стартапов из регионов Казахстана.",
    experience: "Стажировался в венчурном фонде и создал студенческий инвестиционный клуб.",
    motivation_text: "Сильнее других кандидатов ориентирован на влияние через систему возможностей и капитал.",
    essay_excerpt: "Иногда изменение начинается не с большой программы, а с одного формата, который люди захотели посещать каждую неделю.",
    committee_review: {
      requiredApprovals: 3,
      votes: [
        { memberId: "cm-1", memberName: "Алия Нурланова", decision: "approve", rationale: "Сильная инициатива и реальный организационный опыт.", createdAt: "2026-04-05T09:20:00.000Z" },
        { memberId: "cm-2", memberName: "Руслан Жумабек", decision: "hold", rationale: "Нужна более ясная общественная мотивация.", createdAt: "2026-04-05T09:24:00.000Z" },
      ],
      approvedCount: 1,
      rejectCount: 0,
      holdCount: 1,
      finalDecision: "escalated",
      corruptionGuard: "Разделившие мнения кейсы автоматически эскалируются на коллегиальное обсуждение до финального решения.",
    },
    created_at: "2026-04-04T10:30:00.000Z",
    updated_at: "2026-04-05T09:24:00.000Z",
  },
  {
    id: "cand-zarina-nurmagambet",
    code: "IU-2605",
    name: "Зарина Нурмагамбет",
    city: "Павлодар",
    program: "Youth Wellbeing",
    status: "in_progress",
    final_score: 64.1,
    cognitive: 66,
    leadership: 71,
    growth: 76,
    decision: 61,
    motivation: 82,
    authenticity: 81,
    confidence: 0.69,
    ai_detection_prob: 0.17,
    ai_signals: [
      "Высокая личная мотивация",
      "Хорошие сигналы authenticity по живым ответам",
      "Интервью еще не завершено, итог не финальный",
    ],
    needs_manual_review: false,
    reasoning: "Перспективный кандидат с хорошей аутентичностью и общественной мотивацией, но профиль еще не завершен и не должен сравниваться как финальный.",
    key_quotes: [
      "Мне важно, чтобы психологическая помощь в малых городах была не роскошью, а нормой.",
      "У меня есть энергия и идея, но мне нужна структура, чтобы это выросло в систему.",
    ],
    goals: "Построить сеть психологической поддержки для молодежи в малых городах.",
    experience: "Волонтер кризисного центра и автор подкаста о психическом здоровье.",
    motivation_text: "Ищет программу как среду роста и масштабирования собственной инициативы.",
    essay_excerpt: "Я вижу не только проблему, но и людей, которые перестали верить, что помощь может быть рядом.",
    committee_review: {
      requiredApprovals: 3,
      votes: [],
      approvedCount: 0,
      rejectCount: 0,
      holdCount: 0,
      finalDecision: "pending",
      corruptionGuard: "Кандидат не рассматривается как финальный без завершенного интервью и полного пакета данных.",
    },
    created_at: "2026-04-04T10:40:00.000Z",
    updated_at: "2026-04-05T08:20:00.000Z",
  },
];